_home:
    pattern:  /
    defaults: { _controller: AppWebBundle:Post:index }

_signup:
  pattern: /signup
  defaults: { _controller: AppWebBundle:User:signup }

_check:
  pattern: /login_check

_logout:
  pattern: /logout

_activate:
  pattern: /activate
  defaults: { _controller: AppWebBundle:User:activate }

_signin:
  pattern: /signin
  defaults: { _controller: AppWebBundle:User:signin }
  
_forgotten_password:
  pattern: /forgotten-password
  defaults: { _controller: AppWebBundle:User:forgotten_password }

_category:
  pattern: /{slug}/{category_id}
  defaults: { _controller: AppWebBundle:Post:index }

_tag:
  pattern: /tag/{tag_id}-{tag}
  defaults: { _controller: AppWebBundle:Post:index }

_post:
  pattern: /article/{slug}/{post_id}
  defaults: { _controller: AppWebBundle:Post:show }

_profile:
  pattern: /profile
  defaults: { _controller: AppWebBundle:User:profile }

_comments:
  pattern: /comments
  defaults: { _controller: AppWebBundle:User:comments }

_comment_edit:
  pattern: /comment/e/{comment_id}
  defaults: { _controller: AppWebBundle:User:commentEdit }

_comment_delete:
  pattern: /comment/d/{comment_id}
  defaults: { _controller: AppWebBundle:User:commentDelete }

_posts:
  pattern: /posts
  defaults: { _controller: AppWebBundle:User:posts }

_post_edit:
  pattern: /post/e/{post_id}
  defaults: { _controller: AppWebBundle:User:postEdit }

_post_delete:
  pattern: /post/d/{post_id}
  defaults: { _controller: AppWebBundle:User:postDelete }
