_home:
    pattern:  /
    defaults: { _controller: AppWebBundle:Default:index }

_signup:
  pattern: /signup
  defaults: { _controller: AppWebBundle:User:signup }
  
_category:
  pattern: /{category_id}-{slug}
  defaults: { _controller: AppWebBundle:Default:index }

_subcategory:
  pattern: /{category_id}-{slug}/{subcategory_id}-{subslug}
  defaults: { _controller: AppWebBundle:Default:index }

_tag:
  pattern: /tag/{tag_id}-{tag}
  defaults: { _controller: AppWebBundle:Default:index }
