security:
    encoders:
        App\CoreBundle\Entity\User: md5

    providers:
      main:
        entity: { class: App\CoreBundle\Entity\User, property: username }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_MODERATE
        ROLE_MODERATE:    ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MODERATE, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    acl:
        connection: default

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false
            
        configurator:
            pattern: ^/_configurator
            security: false
            
        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:    ^/admin.*
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
            logout:
                path:   /admin/logout
                target: /admin
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
      - { path: /admin.*, roles: [ROLE_MODERATE] }
      - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
